bookers2/config/routes.rb
Rails.application.routes.draw do

  # get 'users/edit'

  root to:'homes#top'
  get '/home/about' => 'users#about'

  devise_for :users
  resources :users, only:[:edit,:update]

  # ユーザー一覧
  get 'users' => 'users#userindex'
  #1ユーザーの投稿一覧
  get 'users/:id' => 'users#usershow', as: 'usershow'

  resources :books, only:[:create,:update,:destroy]

  # 投稿一覧
  get 'books' => 'users#bookindex', as: 'bookindex'

  # 現在のユーザーの投稿詳細
  get 'books/:id' => 'books#show', as: 'bookshow'
  post 'books/:id/favorites/' => 'favorites#create'
  delete 'books/:id/favorites/' => 'favorites#destroy', as: 'book_favorites'
  post 'books/:book_id/post_comments' => 'book_comments#create', as: 'book_book_comments'
  delete 'books/:book_id/post_comments/:id' => 'book_comments#destroy', as: 'book_book_comment'

  get 'books/:id/edit' => 'books#edit'
  post 'books/:id/edit' => 'books#edit', as: 'edit_book'







end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true,
                   length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except:[:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    usershow_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    redirect_to bookshow_path(@book.id)
  end

  def destroy
    book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    book_comment.destroy
    redirect_to bookshow_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      user_id = current_user.id
      @user = User.find_by(id:user_id)
      @newbook = Book.new
      @books = Book.all
      render 'users/bookindex'
    end
  end

  def show
    @book = Book.find(params[:id])
    user_id = @book.user_id
    @user = User.find(user_id)
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to bookindex_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have editted book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to bookindex_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location:root_path)
  end

  def destroy
    book = Book.find(params[:id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location:root_path)
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def userindex
    @user_id = current_user.id
    @user = User.find(@user_id)
    @newbook = Book.new
    @users = User.all
  end

  def bookindex
    @book = Book.new
    user_id = current_user.id
    @user = User.find_by(id:user_id)
    @newbook = Book.new
    @books = Book.all
  end

  def about
  end

  def usershow
    @user = User.find(params[:id])
    @user_id = @user.id
    @books = Book.where(user_id:@user_id)
    @newbook = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to usershow_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have editted user info successfully."
      redirect_to usershow_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
        <% @book.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% end %>

      <%= form_with model:@book,local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Update Book', :class => 'btn btn-success' %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", bookindex_path %>

    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<% if @book.errors.any? %>
  <h2 class="error_text"><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
  <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li class="error_text"><%= message %></li>
    </ul>
  <% end %>
<% end %>

<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %>
        <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:@newbook,local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <% book = @book%>
            <td>
              <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %></br>
              <%= link_to @user.name,usershow_path(@user.id) %>
            </td>
            <td>
              <%= book.title %>
            </td>
            <td>
              <%= book.body %>
            </td>
            <% if book.user == current_user %>
              <td>
                <%= link_to 'Edit',edit_book_path(book), :class => 'btn btn-sm btn-success' %>
              </td>
              <td>
                <%= link_to 'Destroy',"/books/#{book.id}", data:{confirm:"本当に消しますか？"}, :class => 'btn btn-sm btn-danger',method: :delete %>
              </td>
            <% end %>
            <td>
              <% if book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(book.id), method: :delete do %>
                    ❤️<%= book.favorites.count %>
                  <% end %>
                </p>
              <% else %>
                <p>
                  <%= link_to book_favorites_path(book.id), method: :post do %>
                    ️💙<%= book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              コメント数：<%= book.book_comments.count %>
            </td>
          </tr>
        </tbody>
      </table>

      <div>
        <% @book.book_comments.each do |book_comment| %>
          <table>
            <tr>
              <td>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %></br>
                <%= book_comment.user.name %>
              </td>
              <td>
                <%= book_comment.comment %></br>
                <% if book_comment.user == current_user %>
                  <div>
                    <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
                  </div>
                <% end %>
              </td>
            </tr>
          </table>
        <% end %>
      </div>

      <div>
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment %>
          <%= f.submit "送信" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

bookers2/app/views/homes/top.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        in
        <i class="fas fa-book"></i>
        <strong>Bookers,</strong>
        ,
      </p>
      <p>
        you can share and exchange your opinions, impressions, and emotions
      </p>
      <p>
        about various books!
      </p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in",new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in'  %>
        </div>
        <div class="row">
          <%= link_to "Sign up",new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up'  %>
        </div>
      </div>

    </div>
  </div>
</div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Home", usershow_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Users",'/users', class: 'fas fa-users nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Books",bookindex_path, class: 'fas fa-book-open nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "logout",destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light',method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Home",'/', class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "About",'/home/about', class: 'fas fa-link nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "sign up",new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "login",new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

bookers2/app/views/users/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers!</strong>
    </h1>
  </div>
</div>

bookers2/app/views/users/bookindex.html.erb
<% if @book.errors.any? %>
  <h2 class="error_text"><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
  <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li class="error_text"><%= message %></li>
    </ul>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %>
      <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:@newbook,local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book|%>
            <tr>
              <td>
                <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60'), usershow_path(book.user.id) %>
              </td>
              <td><%= link_to book.title,bookshow_path(book.id)  %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book.id), method: :delete do %>
                      ❤️<%= book.favorites.count %>
                    <% end %>
                  </p>
                <% else %>
                  <p>
                    <%= link_to book_favorites_path(book.id), method: :post do %>
                      ️💙<%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

bookers2/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <%= @user.errors.count %> errors prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% end %>

      <%= form_with model:@user ,local:true do |f| %>

        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, :class => 'form-control', :id => 'user_name' %>
        </div>

        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", :class => 'form-control-file user_image' %>
        </div>

        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, :class => 'form-control introduction', :id => 'user_introduction' %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", :class => 'btn btn-secondary' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

bookers2/app/views/users/userindex.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %>
        <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:@newbook,local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user|%>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show",usershow_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/users/usershow.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <p id="notice"><%= flash[:notice] %></p>
  </div>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %>
      <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:@newbook,local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book|%>
            <tr>
              <td>
                <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60'), usershow_path(book.user.id) %>
              </td>
              <td><%= link_to book.title,bookshow_path(book.id)  %></td>
              <td><%= book.body %></td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>